title: "Coding Room"
author: "Coding Room"
description: "Coding Room is a dedicated platform designed to provide comprehensive coding tutorials and resources for learners of all levels. Our mission is to make coding accessible and enjoyable for everyone, regardless of their background or experience level."
image: "/assets/images/icons/logo.png"
permalink: /:title/
lang: "en"
# excerpt_separator: "<!-- Read More -->"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "search.html", icon: search, title: About}
  - {file: "index.html", title: Home}
  - {file: "about.html", title: About}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: thebadalkumar@zohomail.in, icon: envelope, url: "mailto:thebadalkumar@zohomail.in"} #Don't Change this position affect mailing to other pages
  - {title: Youtube, icon: youtube, url: "https://www.youtube.com/@codingroom_"}
  - {title: Facebook, icon: facebook, url: "https://www.facebook.com/roomofcode"}
  - {title: Linkedin, icon: linkedin, url: "https://www.linkedin.com/company/roomofcode/"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/roomofcode/"}
  - {title: Instagram, icon: instagram, url: "https://www.instagram.com/roomofcode/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

url: "https://codingroom.in" # the base hostname & protocol for your site
host: "0.0.0.0"
plugins:
 - jekyll-seo-tag
 - jekyll-feed
 - jekyll-paginate
 - jekyll-sitemap

paginate: 10